# Schema for the configuration of the Icon field type and associated plugins.

field.storage_settings.ex_icon:
  type: mapping
  label: 'Icon field storage settings'
  mapping:
    case_sensitive:
      type: boolean
      label: 'Case sensitive'
    add_title:
      type: boolean
      label: 'Show a text input to enhance the icon value meaning'

field.field_settings.ex_icon:
  type: mapping
  label: 'Icon field settings'

field.value.ex_icon:
  type: mapping
  label: 'Icon default value'
  mapping:
    value:
      type: string
      label: 'Icon ID'
    title:
      type: string
      label: 'Semantic meaning'

field.formatter.settings.ex_icon_default:
  type: mapping
  label: 'Icon field default formatter settings'
  mapping:
    classes:
      type: string
      label: 'HTML classes'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'

field.formatter.settings.ex_icon_link:
  type: field.formatter.settings.link
  mapping:
    icon:
      type: string
    width:
      type: integer
    height:
      type: integer

field.widget.settings.ex_icon_select:
  type: mapping
  label: 'Icon field widget settings'
